class KeyConstants:
    SWAPI_FILMS = 'films'
    SWAPI_PEOPLE = 'people'
    SWAPI_PLANETS = 'planets'
    SWAPI_SPECIES = 'species'
    SWAPI_STARSHIPS = 'starships'
    SWAPI_VEHICLES = 'vehicles'
    SWAPI_PAGE = 'page'
    SWAPI_ITEMS_PER_PAGE = 'items_per_page'
    SWAPI_SORT = 'sort'
    SWAPI_ORDER = 'order'
    SWAPI_SEARCH = 'search'
    SWAPI_RESULTS = 'results'
    SWAPI_NEXT = 'next'
